//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DepartmentID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Credits { get; set; }
    }
}
